import { VideoProject } from "@/types/videos";

// export const videoProjectsData = {
//   "Talking Head": [
//     {
//       id: "rVVeLdouViU",
//       video_title: "একজন ফেসবুক ইঞ্জিনিয়ারের রিজিউমি কেমন হয়?",
//       video_description: `How to Build Your Perfect Resume: Learn from a FAANG Employee Example! Are you ready to take your career to new heights and secure your dream job at a top tech company? Join us on this exclusive journey inside the mind of a FAANG employee as we unveil the secrets of their perfect resume! In this eye-opening video, you\"ll discover the exact strategies and tips used by the industry\"s finest to stand out from the crowd and impress recruiters.`,
//       tags: ["Talking Head", "Explainer"],
//       cover_image: "rVVeLdouViU",
//       publish_date: "2024-08-04",
//       client_name: "Stack Learner",
//       client_image: "/companies/sl-logo.png",
//       client_feedback: "",
//       video_link: "https://youtu.be/rVVeLdouViU?si=LwWPmI4F34mwLNw8",
//       project_images: [],
//       category: "Talking Head",
//       duration: "6:32",
//       software_used: ["DaVinci Resolve"],
//     },
//     {
//       id: "JSZmQxg3fos",
//       video_title: "Mastering DSA for Developers | Last Call to Join",
//       video_description:
//         "This workshop helps application developers explore DSA through real-world problems, connecting data structures to business challenges and fostering a problem-solving mindset for practical solutions.",
//       tags: ["Talking Head", "Explainer"],
//       cover_image: "JSZmQxg3fos",
//       publish_date: "2024-04-08",
//       client_name: "Stack Learner",
//       client_image: "/companies/sl-logo.png",
//       client_feedback: "",
//       video_link: "https://youtu.be/JSZmQxg3fos?si=NZYmG1g4mZiYx6Eb",
//       project_images: [],
//       category: "Talking Head",
//       duration: "10:12",
//       software_used: ["Davinci Resolve", "After Effects"],
//     },
//     {
//       id: "ufRtWGd0cXo",
//       video_title:
//         "Calm Your Nervous System in 60 Seconds with HeartMath Technique | Angela ORR",
//       video_description: `Discover the powerful HeartMath technique to calm your nervous system in just 60 seconds! This quick and effective method can help reduce anxiety, stress, and feelings of overwhelm, promoting a sense of relaxation and calmness. Learn how to regulate your heart rate, slow down your breathing, and quiet your mind with this simple yet profound technique. Perfect for anyone looking to manage stress, improve sleep, or simply feel more centered and grounded in your daily life. Try it now and experience the tranquility you deserve!`,
//       tags: ["Talking Head", "Explainer"],
//       cover_image: "ufRtWGd0cXo",
//       publish_date: "2025-06-06",
//       client_name: "Growthleo",
//       client_image: "/companies/growthleo.png",
//       client_feedback: "",
//       video_link: "https://youtu.be/ufRtWGd0cXo?si=kgVACrMZQ24tUook",
//       project_images: [],
//       category: "Talking Head",
//       duration: "7:18",
//       software_used: ["Davinci Resolve"],
//     },
//     {
//       id: "7OuSRaIPOds",
//       video_title:
//         "The Real Reason You Can’t Change (And How to Fix It in 21 Days) | Angela Orr",
//       video_description: `You\"ve tried every habit hack, diet, and self-help book—but real change still feels impossible. Why? Because you\"re trying to change your behavior without changing your identity.`,
//       tags: ["Talking Head", "Explainer"],
//       cover_image: "7OuSRaIPOds",
//       publish_date: "2025-06-20",
//       client_name: "Growthleo",
//       client_image: "/companies/growthleo.png",
//       client_feedback: "",
//       video_link: "https://youtu.be/7OuSRaIPOds?si=TYMRxpKAbbjU9edP",
//       project_images: [],
//       category: "Talking Head",
//       duration: "8:13",
//       software_used: ["Davinci Resolve"],
//     },
//     {
//       id: "esjJzKjx9Fo",
//       video_title:
//         "From Stuck to Strong: The Brain Reset You Need | Angela Orr",
//       video_description: `Feeling stuck, lost, or like your best years are behind you? You\"re not alone and you\"re not too late.`,
//       tags: ["Talking Head", "Explainer"],
//       cover_image: "esjJzKjx9Fo",
//       publish_date: "2025-07-11",
//       client_name: "Growthleo",
//       client_image: "/companies/growthleo.png",
//       client_feedback: "",
//       video_link: "https://youtu.be/esjJzKjx9Fo?si=Z5IOTm-x-RAB018K",
//       project_images: [],
//       category: "Talking Head",
//       duration: "7:59",
//       software_used: ["Davinci Resolve"],
//     },
//   ],
//   Shorts: [
//     {
//       id: "Qwwgg_qt5ew",
//       video_title: "Apply logic to simplify your conditional problems",
//       video_description:
//         "Apply logic to simplify your conditional problems. Watch the video to understand how!",
//       tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
//       cover_image: "Qwwgg_qt5ew",
//       publish_date: "2024-01-16",
//       client_name: "Stack Learner",
//       client_image: "/companies/sl-logo.png",
//       client_feedback: "",
//       video_link: "https://youtube.com/shorts/Qwwgg_qt5ew?si=tTSoTUnuVPdjpc7y",
//       project_images: [],
//       category: "Shorts",
//       duration: "2:44",
//       software_used: ["DaVinci Resolve"],
//     },
//   ],
//   VSL & ADS: [
//     {
//       id: "kpJyIq-mvtc",
//       video_title: "EduNurture360 কি? | Edu Bridge Academy",
//       video_description: "শুরু হয়ে গেছে EduNurture360 এর ২০২৪ সালের ব্যাচ!",
//       tags: ["VSL & ADS", "Branding", "Cinematic", "Professional"],
//       cover_image: "kpJyIq-mvtc",
//       publish_date: "2024-02-01",
//       client_name: "Edu Bridge Academy",
//       client_image: "/companies/edu-bridge-academy.jpg",
//       client_feedback: "",
//       video_link: "https://youtu.be/kpJyIq-mvtc?si=wdURtwH9HI1FZmOR",
//       project_images: [],
//       category: "VSL & ADS",
//       duration: "1:28",
//       software_used: ["DaVinci Resolve", "After Effects"],
//     },
//     {
//       id: "w72TzfYIsgU",
//       video_title:
//         "Bangladesh’s First Flexible Discount for EdTech – Learn Without Limits!",
//       video_description: `Bangladesh\"s First Flexible Discount for EdTech – Learn Without Limits! We are proud to announce the launch of our brand-new feature, the \"Flexible Discount System,\" a unique feature never seen before in Bangladesh!`,
//       tags: ["Motion Graphics", "VSL & ADS"],
//       cover_image: "w72TzfYIsgU",
//       publish_date: "2025-01-19",
//       client_name: "Stack Learner",
//       client_image: "/companies/stack-learner.png",
//       client_feedback: "",
//       video_link: "https://youtu.be/w72TzfYIsgU?si=50Iu8TME6mC4iH8z",
//       project_images: [],
//       category: "VSL & ADS",
//       duration: "1:29",
//       software_used: ["After Effect"],
//     },
//   ],
//   Documentary: [
//     {
//       id: "Y3lWN7oFkpw",
//       video_title: "EcoRevolution Documentary",
//       video_description:
//         "A compelling documentary exploring environmental sustainability and the revolution towards eco-friendly practices in modern society.",
//       tags: ["Documentary", "Storytelling", "Interviews", "Cinematic"],
//       cover_image: "Y3lWN7oFkpw",
//       publish_date: "2024-04-12",
//       client_name: "EcoRevolution",
//       client_image: "/companies/eco-revolution.jpg",
//       client_feedback: "",
//       video_link: "https://youtu.be/Y3lWN7oFkpw",
//       project_images: [],
//       category: "Documentary",
//       duration: "3:51",
//       software_used: ["DaVinci Resolve", "Audition"],
//     },
//   ],
//   Explainer: [
//     {
//       id: "MCD9uyZT8Y0",
//       video_title: "প্রোগ্রামিং এর ফান্ডামেন্টাল শেখা কেন জরুরী?",
//       video_description: `আমাদের অনেকের মধ্যে common একটা সমস্যা হলো ফান্ডামেন্টাল না শিখেই কাজ শেখা শুরু করে দেই। ফলাফলস্বরূপ একটা স্টেপ পর্যন্ত পৌঁছানোর পর আমরা আর সামনে আগাতে পারি না। যার কারণে অনেকেই হাল ছেড়ে দেয় আবার অনেকে লেগে থাকে। এই ভিডিওতে আমরা এই বিষয়টাই বুঝার চেষ্টা করবো কেনো ফান্ডামেন্টাল শেখা এত বেশি গুরুত্বপূর্ণ।`,
//       tags: ["Explainer", "Education", "Animation", "Voiceover"],
//       cover_image: "MCD9uyZT8Y0",
//       publish_date: "2024-01-19",
//       client_name: "Stack Learner",
//       client_image: "/companies/sl-logo.png",
//       client_feedback:
//         "Fantastic work! Made complex topics easy to understand with great visuals. The explainer video helped our students grasp fundamental concepts much better.",
//       video_link: "https://youtu.be/MCD9uyZT8Y0?si=W6HDf429dZo7hSQM",
//       project_images: [],
//       category: "Explainer",
//       duration: "2:43",
//       software_used: ["After Effects", "Premiere Pro"],
//     },
//   ],
//   "Motion Graphics": [
//     {
//       id: "i2JZPZ-a_tc",
//       video_title: "Business Email Service",
//       video_description: `একটি ভুল ইমেইল কনফিগারেশনের কারণে নষ্ট হতে পারে আপনার সবচেয়ে valuable ক্লায়েন্ট ও ব্যবসার সুনাম। জি, আপনি ঠিকই শুনেছেন — ইমেইল সিস্টেম ছোট মনে হলেও, এর প্রভাব অনেক বড়। তবে চিন্তা করবেন না।`,
//       tags: ["Motion Graphics", "VSL & ADS", "Ads"],
//       cover_image: "i2JZPZ-a_tc",
//       publish_date: "2025-07-25",
//       client_name: "Impel IT",
//       client_image: "/companies/impel-it.png",
//       client_feedback: "",
//       video_link: "https://youtu.be/i2JZPZ-a_tc",
//       project_images: [],
//       category: "Motion Graphics",
//       duration: "1:28",
//       software_used: ["After effects"],
//     },
//     {
//       id: "H29MJ6vLbcg",
//       video_title: "Stack Learner Brand Intro",
//       video_description:
//         "Professional brand introduction animation for Stack Learner with modern motion graphics and smooth transitions.",
//       tags: ["Logo Animation", "Motion Graphics", "Branding", "Animation"],
//       cover_image: "H29MJ6vLbcg",
//       publish_date: "2024-04-12",
//       client_name: "Stack Learner",
//       client_image: "/companies/sl-logo.png",
//       client_feedback: "",
//       video_link: "https://youtu.be/H29MJ6vLbcg",
//       project_images: [],
//       category: "Motion Graphics",
//       duration: "0:22",
//       software_used: ["After Effects"],
//     },
//     {
//       id: "TInQK-60l2A",
//       video_title: "Web & E-commerce Store Development",
//       video_description: `প্রথম ৫ সেকেন্ডেই ভিজিটর ঠিক করে ফেলে—আপনার ক্লায়েন্ট হবে, নাকি সাইট ছেড়ে চলে যাবে। আর তাই, ওয়েবসাইট হতে হয় ফাস্ট, স্মার্ট, ও ইনটুইটিভ। আমাদের দীর্ঘ ১০+ বছরের অভিজ্ঞতা থেকে আপনার জন্য এমন ওয়েবসাইট তৈরি করে দিচ্ছি যাতে শুধু text আর image থাকবে না, থাকবে আপনার ব্র্যান্ডিং ও ইউজারের সমস্যার সমাধান।`,
//       tags: ["Motion Graphics", "VSL & ADS", "Ads"],
//       cover_image: "TInQK-60l2A",
//       publish_date: "2025-07-25",
//       client_name: "Impel IT",
//       client_image: "/companies/impel-it.png",
//       client_feedback: "",
//       video_link: "https://youtu.be/TInQK-60l2A",
//       project_images: [],
//       category: "Motion Graphics",
//       duration: "1:21",
//       software_used: ["After effects"],
//     },
//     {
//       id: "byQmrdAwFK8",
//       video_title: "Digital Marketing",
//       video_description: `ভিজিটর আসছে, কিন্তু কাস্টমার হচ্ছে না? সমস্যা প্রোডাক্টে না, মার্কেটিং সিস্টেমে। Miraco Tech দিচ্ছে Total Digital Marketing Solution, যা কনটেন্ট নয়, কনভার্সন ফোকাসড কমিউনিকেশন তৈরি করে।`,
//       tags: ["Motion Graphics", "VSL & ADS", "Ads"],
//       cover_image: "byQmrdAwFK8",
//       publish_date: "2025-07-25",
//       client_name: "Impel IT",
//       client_image: "/companies/impel-it.png",
//       client_feedback: "",
//       video_link: "https://youtu.be/byQmrdAwFK8",
//       project_images: [],
//       category: "Motion Graphics",
//       duration: "1:22",
//       software_used: ["After effects"],
//     },
//   ],
// };



// export const allVideoProjects: VideoProject[] = [
//   {
//     id: "rVVeLdouViU",
//     video_title: "একজন ফেসবুক ইঞ্জিনিয়ারের রিজিউমি কেমন হয়?",
//     video_description: `How to Build Your Perfect Resume: Learn from a FAANG Employee Example! Are you ready to take your career to new heights and secure your dream job at a top tech company? Join us on this exclusive journey inside the mind of a FAANG employee as we unveil the secrets of their perfect resume! In this eye-opening video, you\"ll discover the exact strategies and tips used by the industry\"s finest to stand out from the crowd and impress recruiters.`,
//     tags: ["Talking Head", "Explainer"],
//     cover_image: "rVVeLdouViU",
//     publish_date: "2024-08-04",
//     client_name: "Stack Learner",
//     client_image: "/companies/sl-logo.png",
//     client_feedback: "",
//     video_link: "https://youtu.be/rVVeLdouViU?si=LwWPmI4F34mwLNw8",
//     project_images: [],
//     category: ["Talking Head", "Explainer"],
//     duration: "6:32",
//     software_used: ["DaVinci Resolve"],
//   },
//   {
//     id: "JSZmQxg3fos",
//     video_title: "Mastering DSA for Developers | Last Call to Join",
//     video_description:
//       "This workshop helps application developers explore DSA through real-world problems, connecting data structures to business challenges and fostering a problem-solving mindset for practical solutions.",
//     tags: ["Talking Head", "Explainer"],
//     cover_image: "JSZmQxg3fos",
//     publish_date: "2024-04-08",
//     client_name: "Stack Learner",
//     client_image: "/companies/sl-logo.png",
//     client_feedback: "",
//     video_link: "https://youtu.be/JSZmQxg3fos?si=NZYmG1g4mZiYx6Eb",
//     project_images: [],
//     category: ["Talking Head", "Explainer"],
//     duration: "10:12",
//     software_used: ["Davinci Resolve", "After Effects"],
//   },
//   {
//     id: "ufRtWGd0cXo",
//     video_title:
//       "Calm Your Nervous System in 60 Seconds with HeartMath Technique | Angela ORR",
//     video_description: `Discover the powerful HeartMath technique to calm your nervous system in just 60 seconds! This quick and effective method can help reduce anxiety, stress, and feelings of overwhelm, promoting a sense of relaxation and calmness. Learn how to regulate your heart rate, slow down your breathing, and quiet your mind with this simple yet profound technique. Perfect for anyone looking to manage stress, improve sleep, or simply feel more centered and grounded in your daily life. Try it now and experience the tranquility you deserve!`,
//     tags: ["Talking Head", "Explainer"],
//     cover_image: "ufRtWGd0cXo",
//     publish_date: "2025-06-06",
//     client_name: "Growthleo",
//     client_image: "/companies/growthleo.png",
//     client_feedback: "",
//     video_link: "https://youtu.be/ufRtWGd0cXo?si=kgVACrMZQ24tUook",
//     project_images: [],
//     category: ["Talking Head", "Explainer"],
//     duration: "7:18",
//     software_used: ["Davinci Resolve"],
//   },
//   {
//     id: "7OuSRaIPOds",
//     video_title:
//       "The Real Reason You Can’t Change (And How to Fix It in 21 Days) | Angela Orr",
//     video_description: `You\"ve tried every habit hack, diet, and self-help book—but real change still feels impossible. Why? Because you\"re trying to change your behavior without changing your identity.`,
//     tags: ["Talking Head", "Explainer"],
//     cover_image: "7OuSRaIPOds",
//     publish_date: "2025-06-20",
//     client_name: "Growthleo",
//     client_image: "/companies/growthleo.png",
//     client_feedback: "",
//     video_link: "https://youtu.be/7OuSRaIPOds?si=TYMRxpKAbbjU9edP",
//     project_images: [],
//     category: ["Talking Head", "Explainer"],
//     duration: "8:13",
//     software_used: ["Davinci Resolve"],
//   },
//   {
//     id: "esjJzKjx9Fo",
//     video_title: "From Stuck to Strong: The Brain Reset You Need | Angela Orr",
//     video_description: `Feeling stuck, lost, or like your best years are behind you? You\"re not alone and you\"re not too late.`,
//     tags: ["Talking Head", "Explainer"],
//     cover_image: "esjJzKjx9Fo",
//     publish_date: "2025-07-11",
//     client_name: "Growthleo",
//     client_image: "/companies/growthleo.png",
//     client_feedback: "",
//     video_link: "https://youtu.be/esjJzKjx9Fo?si=Z5IOTm-x-RAB018K",
//     project_images: [],
//     category: ["Talking Head", "Explainer"],
//     duration: "7:59",
//     software_used: ["Davinci Resolve"],
//   },
//   {
//     id: "Qwwgg_qt5ew",
//     video_title: "Apply logic to simplify your conditional problems",
//     video_description:
//       "Apply logic to simplify your conditional problems. Watch the video to understand how!",
//     tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
//     cover_image: "Qwwgg_qt5ew",
//     publish_date: "2024-01-16",
//     client_name: "Stack Learner",
//     client_image: "/companies/sl-logo.png",
//     client_feedback: "",
//     video_link: "https://youtube.com/shorts/Qwwgg_qt5ew?si=tTSoTUnuVPdjpc7y",
//     project_images: [],
//     category: ["Shorts", "Motion Graphics", "Explainer"],
//     duration: "2:44",
//     software_used: ["After Effects"],
//   },
//   {
//     id: "kpJyIq-mvtc",
//     video_title: "EduNurture360 কি? | Edu Bridge Academy",
//     video_description: "শুরু হয়ে গেছে EduNurture360 এর ২০২৪ সালের ব্যাচ!",
//     tags: ["VSL & ADS", "Branding", "Cinematic", "Professional"],
//     cover_image: "kpJyIq-mvtc",
//     publish_date: "2024-02-01",
//     client_name: "Edu Bridge Academy",
//     client_image: "/companies/edu-bridge-academy.jpg",
//     client_feedback: "",
//     video_link: "https://youtu.be/kpJyIq-mvtc?si=wdURtwH9HI1FZmOR",
//     project_images: [],
//     category: ["VSL & ADS", "Motion Graphics"],
//     duration: "1:28",
//     software_used: ["After Effects"],
//   },
//   {
//     id: "w72TzfYIsgU",
//     video_title:
//       "Bangladesh’s First Flexible Discount for EdTech – Learn Without Limits!",
//     video_description: `Bangladesh\"s First Flexible Discount for EdTech – Learn Without Limits! We are proud to announce the launch of our brand-new feature, the \"Flexible Discount System,\" a unique feature never seen before in Bangladesh!`,
//     tags: ["Motion Graphics", "VSL & ADS"],
//     cover_image: "w72TzfYIsgU",
//     publish_date: "2025-01-19",
//     client_name: "Stack Learner",
//     client_image: "/companies/sl-logo.png",
//     client_feedback: "",
//     video_link: "https://youtu.be/w72TzfYIsgU?si=50Iu8TME6mC4iH8z",
//     project_images: [],
//     category: ["VSL & ADS", "Motion Graphics"],
//     duration: "1:29",
//     software_used: ["After Effect"],
//   },
//   {
//     id: "Y3lWN7oFkpw",
//     video_title: "EcoRevolution Documentary",
//     video_description:
//       "A compelling documentary exploring environmental sustainability and the revolution towards eco-friendly practices in modern society.",
//     tags: ["Documentary", "Storytelling", "Interviews", "Cinematic"],
//     cover_image: "Y3lWN7oFkpw",
//     publish_date: "2024-04-12",
//     client_name: "EcoRevolution",
//     client_image: "/companies/eco-revolution.jpg",
//     client_feedback: "",
//     video_link: "https://youtu.be/Y3lWN7oFkpw",
//     project_images: [],
//     category: ["Documentary", "Motion Graphics"],
//     duration: "3:51",
//     software_used: ["After Effects"],
//   },
//   {
//     id: "MCD9uyZT8Y0",
//     video_title: "প্রোগ্রামিং এর ফান্ডামেন্টাল শেখা কেন জরুরী?",
//     video_description: `আমাদের অনেকের মধ্যে common একটা সমস্যা হলো ফান্ডামেন্টাল না শিখেই কাজ শেখা শুরু করে দেই। ফলাফলস্বরূপ একটা স্টেপ পর্যন্ত পৌঁছানোর পর আমরা আর সামনে আগাতে পারি না। যার কারণে অনেকেই হাল ছেড়ে দেয় আবার অনেকে লেগে থাকে। এই ভিডিওতে আমরা এই বিষয়টাই বুঝার চেষ্টা করবো কেনো ফান্ডামেন্টাল শেখা এত বেশি গুরুত্বপূর্ণ।`,
//     tags: ["Explainer", "Education", "Animation", "Voiceover"],
//     cover_image: "MCD9uyZT8Y0",
//     publish_date: "2024-01-19",
//     client_name: "Stack Learner",
//     client_image: "/companies/sl-logo.png",
//     client_feedback:
//       "Fantastic work! Made complex topics easy to understand with great visuals. The explainer video helped our students grasp fundamental concepts much better.",
//     video_link: "https://youtu.be/MCD9uyZT8Y0?si=W6HDf429dZo7hSQM",
//     project_images: [],
//     category: ["Explainer", "Motion Graphics"],
//     duration: "2:43",
//     software_used: ["Davinci Resolve"],
//   },
//   {
//     id: "i2JZPZ-a_tc",
//     video_title: "Business Email Service",
//     video_description: `একটি ভুল ইমেইল কনফিগারেশনের কারণে নষ্ট হতে পারে আপনার সবচেয়ে valuable ক্লায়েন্ট ও ব্যবসার সুনাম। জি, আপনি ঠিকই শুনেছেন — ইমেইল সিস্টেম ছোট মনে হলেও, এর প্রভাব অনেক বড়। তবে চিন্তা করবেন না।`,
//     tags: ["Motion Graphics", "VSL & ADS", "Ads"],
//     cover_image: "i2JZPZ-a_tc",
//     publish_date: "2025-07-25",
//     client_name: "Impel IT",
//     client_image: "/companies/impel-it.png",
//     client_feedback: "",
//     video_link: "https://youtu.be/i2JZPZ-a_tc",
//     project_images: [],
//     category: ["Motion Graphics", "VSL & ADS"],
//     duration: "1:28",
//     software_used: ["After effects"],
//   },
//   {
//     id: "H29MJ6vLbcg",
//     video_title: "Stack Learner Brand Intro",
//     video_description:
//       "Professional brand introduction animation for Stack Learner with modern motion graphics and smooth transitions.",
//     tags: ["Logo Animation", "Motion Graphics", "Branding", "Animation"],
//     cover_image: "H29MJ6vLbcg",
//     publish_date: "2024-04-12",
//     client_name: "Stack Learner",
//     client_image: "/companies/sl-logo.png",
//     client_feedback: "",
//     video_link: "https://youtu.be/H29MJ6vLbcg",
//     project_images: [],
//     category: ["Motion Graphics"],
//     duration: "0:22",
//     software_used: ["After Effects"],
//   },
//   {
//     id: "TInQK-60l2A",
//     video_title: "Web & E-commerce Store Development",
//     video_description: `প্রথম ৫ সেকেন্ডেই ভিজিটর ঠিক করে ফেলে—আপনার ক্লায়েন্ট হবে, নাকি সাইট ছেড়ে চলে যাবে। আর তাই, ওয়েবসাইট হতে হয় ফাস্ট, স্মার্ট, ও ইনটুইটিভ। আমাদের দীর্ঘ ১০+ বছরের অভিজ্ঞতা থেকে আপনার জন্য এমন ওয়েবসাইট তৈরি করে দিচ্ছি যাতে শুধু text আর image থাকবে না, থাকবে আপনার ব্র্যান্ডিং ও ইউজারের সমস্যার সমাধান।`,
//     tags: ["Motion Graphics", "VSL & ADS", "Ads"],
//     cover_image: "TInQK-60l2A",
//     publish_date: "2025-07-25",
//     client_name: "Impel IT",
//     client_image: "/companies/impel-it.png",
//     client_feedback: "",
//     video_link: "https://youtu.be/TInQK-60l2A",
//     project_images: [],
//     category: ["Motion Graphics", "VSL & ADS"],
//     duration: "1:21",
//     software_used: ["After effects"],
//   },
//   {
//     id: "byQmrdAwFK8",
//     video_title: "Digital Marketing",
//     video_description: `ভিজিটর আসছে, কিন্তু কাস্টমার হচ্ছে না? সমস্যা প্রোডাক্টে না, মার্কেটিং সিস্টেমে। Miraco Tech দিচ্ছে Total Digital Marketing Solution, যা কনটেন্ট নয়, কনভার্সন ফোকাসড কমিউনিকেশন তৈরি করে।`,
//     tags: ["Motion Graphics", "VSL & ADS", "Ads"],
//     cover_image: "byQmrdAwFK8",
//     publish_date: "2025-07-25",
//     client_name: "Impel IT",
//     client_image: "/companies/impel-it.png",
//     client_feedback: "",
//     video_link: "https://youtu.be/byQmrdAwFK8",
//     project_images: [],
//     category: ["Motion Graphics", "VSL & ADS"],
//     duration: "1:22",
//     software_used: ["After effects"],
//   },
// ];
